#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : inih
Version  : 52
Release  : 3
URL      : https://github.com/benhoyt/inih/archive/r52/inih-52.tar.gz
Source0  : https://github.com/benhoyt/inih/archive/r52/inih-52.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: inih-lib = %{version}-%{release}
Requires: inih-license = %{version}-%{release}
BuildRequires : buildreq-meson
Patch1: 0001-Set-project-version.patch

%description
# inih (INI Not Invented Here)
[![TravisCI Build](https://travis-ci.org/benhoyt/inih.svg)](https://travis-ci.org/benhoyt/inih)

%package dev
Summary: dev components for the inih package.
Group: Development
Requires: inih-lib = %{version}-%{release}
Provides: inih-devel = %{version}-%{release}
Requires: inih = %{version}-%{release}

%description dev
dev components for the inih package.


%package lib
Summary: lib components for the inih package.
Group: Libraries
Requires: inih-license = %{version}-%{release}

%description lib
lib components for the inih package.


%package license
Summary: license components for the inih package.
Group: Default

%description license
license components for the inih package.


%prep
%setup -q -n inih-r52
cd %{_builddir}/inih-r52
%patch1 -p1

%build
## build_prepend content
sed -i 's/@PKGVER@/%{version}/' meson.build
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1609792683
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain -Ddefault_library=shared \
-Ddistro_install=true \
-Dwith_INIReader=true  builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/inih
cp %{_builddir}/inih-r52/LICENSE.txt %{buildroot}/usr/share/package-licenses/inih/d097282eb6f05d825f591cef06bac3654b58feba
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/INIReader.h
/usr/include/ini.h
/usr/lib64/libINIReader.so
/usr/lib64/libinih.so
/usr/lib64/pkgconfig/INIReader.pc
/usr/lib64/pkgconfig/inih.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libINIReader.so.0
/usr/lib64/libinih.so.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/inih/d097282eb6f05d825f591cef06bac3654b58feba
